  name: portfolio_site
  description: My Portfolio Site
  version: 0.0.1

  environment:
    sdk: '^3.8.0'

  dependencies:
    dio: ^5.8.0+1
    jaspr: ^0.19.0
    jaspr_content: ^0.2.0
    jaspr_lucide: ^0.4.0
    jaspr_riverpod: ^0.3.20
    jaspr_router: ^0.7.0

  dev_dependencies:
    build_runner: ^2.4.0
    jaspr_web_compilers: ^4.1.5+1
    jaspr_builder: ^0.19.0
    jaspr_lints: ^0.4.0
    jaspr_tailwind: ^0.3.3

  jaspr:
    mode: client
    uses-tailwind: true
