  name: portfolio_site
  description: A new Jaspr project
  version: 0.0.1

  environment:
    sdk: '>=3.0.0 <4.0.0'

  dependencies:
    jaspr: ^0.19.0
    jaspr_content: ^0.2.0
    jaspr_riverpod: ^0.3.20
    jaspr_router: ^0.7.0

  dev_dependencies:
    build_runner: ^2.4.0
    jaspr_web_compilers: ^4.1.5+1
    jaspr_builder: ^0.19.0
    jaspr_lints: ^0.4.0
    jaspr_tailwind: ^0.3.3

  jaspr:
    mode: static
    uses-tailwind: true
